import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import { Header } from "@/components/blocks/header";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import ConfigureAmplifyClientSide from "./amplify-cognito-config";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen w-full font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <ConfigureAmplifyClientSide />
          <div className="bg-secondary w-full h-full min-h-screen flex flex-col items-center justify-start">
            <div className="mt-14 w-full max-w-screen-sm p-6">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
